/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { HopeLike, HopeLikeInterface } from "../HopeLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "hope",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "nope",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class HopeLike__factory {
  static readonly abi = _abi;
  static createInterface(): HopeLikeInterface {
    return new utils.Interface(_abi) as HopeLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HopeLike {
    return new Contract(address, _abi, signerOrProvider) as HopeLike;
  }
}
