/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IERC20Meta, IERC20MetaInterface } from "../IERC20Meta";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC20Meta__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20MetaInterface {
    return new utils.Interface(_abi) as IERC20MetaInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20Meta {
    return new Contract(address, _abi, signerOrProvider) as IERC20Meta;
  }
}
