/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  OZUpgradeTestInitial,
  OZUpgradeTestInitialInterface,
} from "../OZUpgradeTestInitial";

const _abi = [
  {
    inputs: [],
    name: "amount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_tokenAddress",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101f5806100206000396000f3fe6080604052600436106100345760003560e01c8063aa8c217c14610039578063c4d66de814610062578063fc0c546a14610077575b600080fd5b34801561004557600080fd5b5061004f60015481565b6040519081526020015b60405180910390f35b61007561007036600461018f565b6100b5565b005b34801561008357600080fd5b5060005461009d906201000090046001600160a01b031681565b6040516001600160a01b039091168152602001610059565b600054610100900460ff16806100ce575060005460ff16155b6101355760405162461bcd60e51b815260206004820152602e60248201527f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160448201526d191e481a5b9a5d1a585b1a5e995960921b606482015260840160405180910390fd5b600054610100900460ff16158015610157576000805461ffff19166101011790555b6000805462010000600160b01b031916620100006001600160a01b03851602179055801561018b576000805461ff00191690555b5050565b6000602082840312156101a157600080fd5b81356001600160a01b03811681146101b857600080fd5b939250505056fea2646970667358221220d250ce57a879e6495780e8a096914be511425f42e3327dae00f38f18dcb2860e64736f6c63430008090033";

export class OZUpgradeTestInitial__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<OZUpgradeTestInitial> {
    return super.deploy(overrides || {}) as Promise<OZUpgradeTestInitial>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): OZUpgradeTestInitial {
    return super.attach(address) as OZUpgradeTestInitial;
  }
  connect(signer: Signer): OZUpgradeTestInitial__factory {
    return super.connect(signer) as OZUpgradeTestInitial__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OZUpgradeTestInitialInterface {
    return new utils.Interface(_abi) as OZUpgradeTestInitialInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OZUpgradeTestInitial {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OZUpgradeTestInitial;
  }
}
