/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ITransmuterBufferInterface extends ethers.utils.Interface {
  functions: {
    "burnCredit()": FunctionFragment;
    "depositFunds(address,uint256)": FunctionFragment;
    "exchange(address)": FunctionFragment;
    "getAvailableFlow(address)": FunctionFragment;
    "getTotalCredit()": FunctionFragment;
    "getTotalUnderlyingBuffered(address)": FunctionFragment;
    "getWeight(address,address)": FunctionFragment;
    "onERC20Received(address,uint256)": FunctionFragment;
    "refreshStrategies()": FunctionFragment;
    "registerAsset(address,address)": FunctionFragment;
    "setAlchemist(address)": FunctionFragment;
    "setFlowRate(address,uint256)": FunctionFragment;
    "setSource(address,bool)": FunctionFragment;
    "setWeights(address,address[],uint256[])": FunctionFragment;
    "version()": FunctionFragment;
    "withdraw(address,uint256,address)": FunctionFragment;
    "withdrawFromAlchemist(address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "burnCredit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFunds",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "exchange", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAvailableFlow",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCredit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalUnderlyingBuffered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWeight",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC20Received",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "refreshStrategies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAsset",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAlchemist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlowRate",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSource",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setWeights",
    values: [string, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromAlchemist",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "burnCredit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exchange", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableFlow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalUnderlyingBuffered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWeight", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC20Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refreshStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAlchemist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFlowRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSource", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setWeights", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromAlchemist",
    data: BytesLike
  ): Result;

  events: {
    "RefreshStrategies()": EventFragment;
    "RegisterAsset(address,address)": EventFragment;
    "SetAlchemist(address)": EventFragment;
    "SetFlowRate(address,uint256)": EventFragment;
    "SetSource(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RefreshStrategies"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegisterAsset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAlchemist"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetFlowRate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetSource"): EventFragment;
}

export type RefreshStrategiesEvent = TypedEvent<[] & {}>;

export type RegisterAssetEvent = TypedEvent<
  [string, string] & { underlyingToken: string; transmuter: string }
>;

export type SetAlchemistEvent = TypedEvent<[string] & { alchemist: string }>;

export type SetFlowRateEvent = TypedEvent<
  [string, BigNumber] & { underlyingToken: string; flowRate: BigNumber }
>;

export type SetSourceEvent = TypedEvent<
  [string, boolean] & { source: string; flag: boolean }
>;

export class ITransmuterBuffer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ITransmuterBufferInterface;

  functions: {
    burnCredit(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositFunds(
      underlyingToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    exchange(
      underlyingToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAvailableFlow(
      underlyingToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { availableFlow: BigNumber }>;

    getTotalCredit(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTotalUnderlyingBuffered(
      underlyingToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { totalBuffered: BigNumber }>;

    getWeight(
      weightToken: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { weight: BigNumber }>;

    onERC20Received(
      token: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    refreshStrategies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerAsset(
      underlyingToken: string,
      transmuter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAlchemist(
      alchemist: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFlowRate(
      underlyingToken: string,
      flowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSource(
      source: string,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWeights(
      weightToken: string,
      tokens: string[],
      weights: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      underlyingToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawFromAlchemist(
      yieldToken: string,
      shares: BigNumberish,
      minimumAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  burnCredit(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositFunds(
    underlyingToken: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  exchange(
    underlyingToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAvailableFlow(
    underlyingToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalCredit(overrides?: CallOverrides): Promise<BigNumber>;

  getTotalUnderlyingBuffered(
    underlyingToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getWeight(
    weightToken: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  onERC20Received(
    token: string,
    value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  refreshStrategies(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerAsset(
    underlyingToken: string,
    transmuter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAlchemist(
    alchemist: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFlowRate(
    underlyingToken: string,
    flowRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSource(
    source: string,
    flag: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWeights(
    weightToken: string,
    tokens: string[],
    weights: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<string>;

  withdraw(
    underlyingToken: string,
    amount: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawFromAlchemist(
    yieldToken: string,
    shares: BigNumberish,
    minimumAmountOut: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    burnCredit(overrides?: CallOverrides): Promise<void>;

    depositFunds(
      underlyingToken: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    exchange(underlyingToken: string, overrides?: CallOverrides): Promise<void>;

    getAvailableFlow(
      underlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalCredit(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalUnderlyingBuffered(
      underlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWeight(
      weightToken: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC20Received(
      token: string,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    refreshStrategies(overrides?: CallOverrides): Promise<void>;

    registerAsset(
      underlyingToken: string,
      transmuter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAlchemist(alchemist: string, overrides?: CallOverrides): Promise<void>;

    setFlowRate(
      underlyingToken: string,
      flowRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSource(
      source: string,
      flag: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setWeights(
      weightToken: string,
      tokens: string[],
      weights: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<string>;

    withdraw(
      underlyingToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFromAlchemist(
      yieldToken: string,
      shares: BigNumberish,
      minimumAmountOut: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "RefreshStrategies()"(): TypedEventFilter<[], {}>;

    RefreshStrategies(): TypedEventFilter<[], {}>;

    "RegisterAsset(address,address)"(
      underlyingToken?: null,
      transmuter?: null
    ): TypedEventFilter<
      [string, string],
      { underlyingToken: string; transmuter: string }
    >;

    RegisterAsset(
      underlyingToken?: null,
      transmuter?: null
    ): TypedEventFilter<
      [string, string],
      { underlyingToken: string; transmuter: string }
    >;

    "SetAlchemist(address)"(
      alchemist?: null
    ): TypedEventFilter<[string], { alchemist: string }>;

    SetAlchemist(
      alchemist?: null
    ): TypedEventFilter<[string], { alchemist: string }>;

    "SetFlowRate(address,uint256)"(
      underlyingToken?: null,
      flowRate?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { underlyingToken: string; flowRate: BigNumber }
    >;

    SetFlowRate(
      underlyingToken?: null,
      flowRate?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { underlyingToken: string; flowRate: BigNumber }
    >;

    "SetSource(address,bool)"(
      source?: null,
      flag?: null
    ): TypedEventFilter<[string, boolean], { source: string; flag: boolean }>;

    SetSource(
      source?: null,
      flag?: null
    ): TypedEventFilter<[string, boolean], { source: string; flag: boolean }>;
  };

  estimateGas: {
    burnCredit(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositFunds(
      underlyingToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    exchange(
      underlyingToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAvailableFlow(
      underlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalCredit(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalUnderlyingBuffered(
      underlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWeight(
      weightToken: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC20Received(
      token: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    refreshStrategies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerAsset(
      underlyingToken: string,
      transmuter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAlchemist(
      alchemist: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFlowRate(
      underlyingToken: string,
      flowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSource(
      source: string,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWeights(
      weightToken: string,
      tokens: string[],
      weights: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      underlyingToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawFromAlchemist(
      yieldToken: string,
      shares: BigNumberish,
      minimumAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    burnCredit(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositFunds(
      underlyingToken: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    exchange(
      underlyingToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAvailableFlow(
      underlyingToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalCredit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalUnderlyingBuffered(
      underlyingToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWeight(
      weightToken: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC20Received(
      token: string,
      value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    refreshStrategies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerAsset(
      underlyingToken: string,
      transmuter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAlchemist(
      alchemist: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFlowRate(
      underlyingToken: string,
      flowRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSource(
      source: string,
      flag: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWeights(
      weightToken: string,
      tokens: string[],
      weights: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      underlyingToken: string,
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFromAlchemist(
      yieldToken: string,
      shares: BigNumberish,
      minimumAmountOut: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
